from __future__ import annotations

from datetime import datetime, timedelta, timezone

from agent_activity_graph.sdk.events import ActorType, OutcomeStatus, WorkflowEvent


def _invoice_context(
    *,
    invoice_amount: int,
    vendor_id: str,
    vendor_name: str,
    po_number: str | None,
    cost_center: str,
    payment_terms: str,
    invoice_due_date: str,
    payment_batch_cutoff: str,
    risk_category: str,
    business_consequence: str,
    threshold: int,
) -> dict:
    return {
        "invoice_amount": invoice_amount,
        "currency": "USD",
        "vendor_id": vendor_id,
        "vendor_name": vendor_name,
        "po_number": po_number,
        "cost_center": cost_center,
        "payment_terms": payment_terms,
        "invoice_due_date": invoice_due_date,
        "payment_batch_cutoff": payment_batch_cutoff,
        "risk_category": risk_category,
        "business_consequence": business_consequence,
        "agent_approval_threshold": threshold,
    }


def _event(
    *,
    event_id: str,
    minutes: int,
    workflow_id: str,
    business_object_id: str,
    process_step: str,
    actor_type: ActorType,
    actor_id: str,
    actor_name: str,
    action_type: str,
    action_summary: str,
    tool_name: str | None,
    target_system: str | None,
    permission_scope: str,
    authority_subject: str | None = None,
    authority_delegation_source: str | None = None,
    policy_rule_ids: list[str] | None = None,
    review_case_id: str | None = None,
    review_state: str | None = None,
    human_decision_reason: str | None = None,
    decision_code: str | None = None,
    decision_rationale: str | None = None,
    approved_exception_type: str | None = None,
    approver_role: str | None = None,
    remediation_owner: str | None = None,
    remediation_due_by: datetime | None = None,
    closure_status: str | None = None,
    due_by: datetime | None = None,
    source_trace_ref: str | None = None,
    source_system_ref: str | None = None,
    parent_event_id: str | None = None,
    outcome_status: OutcomeStatus = OutcomeStatus.SUCCESS,
    metadata: dict | None = None,
) -> WorkflowEvent:
    base = datetime(2026, 3, 31, 9, 0, tzinfo=timezone.utc)
    return WorkflowEvent(
        event_id=event_id,
        timestamp=base + timedelta(minutes=minutes),
        workflow_id=workflow_id,
        workflow_name="Invoice Approval with Agent Participation",
        process_step=process_step,
        actor_type=actor_type,
        actor_id=actor_id,
        actor_name=actor_name,
        action_type=action_type,
        action_summary=action_summary,
        tool_name=tool_name,
        target_system=target_system,
        business_object_type="invoice",
        business_object_id=business_object_id,
        permission_scope=permission_scope,
        authority_subject=authority_subject,
        authority_delegation_source=authority_delegation_source,
        policy_rule_ids=policy_rule_ids or [],
        review_case_id=review_case_id,
        review_state=review_state,
        human_decision_reason=human_decision_reason,
        decision_code=decision_code,
        decision_rationale=decision_rationale,
        approved_exception_type=approved_exception_type,
        approver_role=approver_role,
        remediation_owner=remediation_owner,
        remediation_due_by=remediation_due_by,
        closure_status=closure_status,
        due_by=due_by,
        source_trace_ref=source_trace_ref or f"trace-demo-{workflow_id}",
        source_system_ref=source_system_ref or target_system,
        parent_event_id=parent_event_id,
        outcome_status=outcome_status,
        metadata=metadata or {},
    )


def invoice_approval_scenario() -> list[WorkflowEvent]:
    threshold = 5000

    normal_context = _invoice_context(
        invoice_amount=3200,
        vendor_id="VENDOR-441",
        vendor_name="Northwind Office Supply",
        po_number="PO-7781",
        cost_center="CORP-OPS-214",
        payment_terms="Net 15",
        invoice_due_date="2026-04-02",
        payment_batch_cutoff="2026-03-31T14:00:00Z",
        risk_category="payment_timing_control",
        business_consequence="If this invoice misses the 14:00 UTC payment cut-off, the supplier loses same-day settlement and AP has to explain the delay.",
        threshold=threshold,
    )
    escalated_context = _invoice_context(
        invoice_amount=18500,
        vendor_id="VENDOR-998",
        vendor_name="Kepler Advisory Group",
        po_number="PO-9921",
        cost_center="FINANCE-TRANSFORM-08",
        payment_terms="Net 10",
        invoice_due_date="2026-03-31",
        payment_batch_cutoff="2026-03-31T14:00:00Z",
        risk_category="delayed_payment_risk",
        business_consequence="If finance approval lands after 14:00 UTC, the invoice misses the same-day payment run and slips at least one business day.",
        threshold=threshold,
    )
    blocked_context = _invoice_context(
        invoice_amount=42000,
        vendor_id="VENDOR-555",
        vendor_name="Atlas Field Services",
        po_number=None,
        cost_center="FIELD-OPS-911",
        payment_terms="Due on receipt",
        invoice_due_date="2026-03-31",
        payment_batch_cutoff="2026-03-31T14:00:00Z",
        risk_category="policy_breach_risk",
        business_consequence="The attempted approval puts the invoice on manual hold, creates a policy breach review, and delays vendor payment by at least one cycle.",
        threshold=threshold,
    )

    return [
        _event(
            event_id="evt_wf_1001_01",
            minutes=0,
            workflow_id="wf-invoice-1001",
            business_object_id="INV-1001",
            process_step="invoice_received",
            actor_type=ActorType.SYSTEM,
            actor_id="ap-inbox",
            actor_name="AP Inbox",
            action_type="invoice_received",
            action_summary="Invoice INV-1001 arrived from Northwind Office Supply with a clean PO reference and standard office spend profile.",
            tool_name="mailroom-adapter",
            target_system="inbox",
            permission_scope="invoice:intake",
            metadata={
                **normal_context,
                "headline": "AP inbox accepted a low-value invoice with a valid PO",
                "why_it_mattered": "The workflow started with the minimum fields needed for an autonomous approval path.",
            },
        ),
        _event(
            event_id="evt_wf_1001_02",
            minutes=2,
            workflow_id="wf-invoice-1001",
            business_object_id="INV-1001",
            process_step="classification",
            actor_type=ActorType.AGENT,
            actor_id="ap-agent",
            actor_name="AP Agent",
            action_type="classify_invoice",
            action_summary="AP Agent classified the invoice as PO-backed indirect spend and routed it into the standard approval lane.",
            tool_name="invoice-classifier",
            target_system="inbox",
            permission_scope="invoice:classify",
            parent_event_id="evt_wf_1001_01",
            metadata={
                **normal_context,
                "headline": "Agent classified the invoice into the normal PO-backed lane",
                "why_it_mattered": "Correct classification determines whether the workflow can stay inside delegated approval authority.",
            },
        ),
        _event(
            event_id="evt_wf_1001_03",
            minutes=5,
            workflow_id="wf-invoice-1001",
            business_object_id="INV-1001",
            process_step="po_check",
            actor_type=ActorType.AGENT,
            actor_id="ap-agent",
            actor_name="AP Agent",
            action_type="check_purchase_order",
            action_summary="AP Agent matched the invoice to PO-7781, confirmed the goods receipt, and found no pricing variance.",
            tool_name="erp-lookup",
            target_system="erp-read",
            permission_scope="erp:read:purchase_orders",
            parent_event_id="evt_wf_1001_02",
            metadata={
                **normal_context,
                "headline": "Agent verified the PO, receipt, and pricing evidence",
                "why_it_mattered": "The approval path is only defensible if the invoice is grounded in ERP evidence, not just document text.",
            },
        ),
        _event(
            event_id="evt_wf_1001_04",
            minutes=7,
            workflow_id="wf-invoice-1001",
            business_object_id="INV-1001",
            process_step="approval_recommendation",
            actor_type=ActorType.AGENT,
            actor_id="ap-agent",
            actor_name="AP Agent",
            action_type="prepare_approval_recommendation",
            action_summary="AP Agent assembled a recommendation packet with the invoice amount, PO match, goods receipt, and delegated approval scope.",
            tool_name="approval-packet-builder",
            target_system="erp-read",
            permission_scope="invoice:approve:proposal",
            authority_subject="AP Agent may prepare approval packets but may not finalize payments without policy clearance.",
            authority_delegation_source="Finance AP delegation policy v2026.03",
            parent_event_id="evt_wf_1001_03",
            metadata={
                **normal_context,
                "headline": "Agent prepared the approval recommendation packet",
                "why_it_mattered": "The recommendation packet is the evidence boundary between agent judgment and the policy gate.",
            },
        ),
        _event(
            event_id="evt_wf_1001_05",
            minutes=8,
            workflow_id="wf-invoice-1001",
            business_object_id="INV-1001",
            process_step="policy_gate",
            actor_type=ActorType.SYSTEM,
            actor_id="policy-engine",
            actor_name="Policy Engine",
            action_type="policy_evaluation",
            action_summary="Policy Engine evaluated the recommendation and cleared autonomous approval because the invoice is below the $5,000 threshold and the required fields are present.",
            tool_name="policy-engine",
            target_system="policy-engine",
            permission_scope="policy:evaluate",
            parent_event_id="evt_wf_1001_04",
            metadata={
                **normal_context,
                "headline": "Policy engine allowed the agent to continue",
                "why_it_mattered": "This is the formal control decision that lets the workflow stay in the agent lane.",
                "candidate_actor_type": "agent",
                "candidate_actor_id": "ap-agent",
                "candidate_action_type": "propose_invoice_approval",
                "candidate_target_system": "erp-approvals",
            },
        ),
        _event(
            event_id="evt_wf_1001_06",
            minutes=9,
            workflow_id="wf-invoice-1001",
            business_object_id="INV-1001",
            process_step="approval_execution",
            actor_type=ActorType.AGENT,
            actor_id="ap-agent",
            actor_name="AP Agent",
            action_type="approve_invoice",
            action_summary="AP Agent approved the invoice under delegated low-value authority and recorded the approval scope used.",
            tool_name="erp-approval-writer",
            target_system="erp-approvals",
            permission_scope="invoice:approve:under_threshold",
            authority_subject="AP Agent is delegated to approve PO-backed invoices up to USD 5,000.",
            authority_delegation_source="Finance AP delegation policy v2026.03",
            parent_event_id="evt_wf_1001_05",
            metadata={
                **normal_context,
                "headline": "Agent executed the approval inside delegated authority",
                "why_it_mattered": "The runtime record shows the approval happened under a narrow, auditable scope rather than an implicit blanket permission.",
            },
        ),
        _event(
            event_id="evt_wf_1001_07",
            minutes=11,
            workflow_id="wf-invoice-1001",
            business_object_id="INV-1001",
            process_step="payment_queue",
            actor_type=ActorType.SYSTEM,
            actor_id="erp",
            actor_name="ERP Scheduler",
            action_type="payment_scheduled",
            action_summary="ERP scheduled the invoice into the same-day payment batch before the 14:00 UTC cut-off.",
            tool_name="erp-scheduler",
            target_system="erp-approvals",
            permission_scope="invoice:payment:schedule",
            parent_event_id="evt_wf_1001_06",
            metadata={
                **normal_context,
                "headline": "System preserved the payment schedule without human intervention",
                "why_it_mattered": "The workflow reached a real business outcome, not just a model output or approval suggestion.",
                "outcome_headline": "Agent-approved invoice reached scheduled payment without a human handoff.",
            },
        ),
        _event(
            event_id="evt_wf_2001_01",
            minutes=20,
            workflow_id="wf-invoice-2001",
            business_object_id="INV-2001",
            process_step="invoice_received",
            actor_type=ActorType.SYSTEM,
            actor_id="ap-inbox",
            actor_name="AP Inbox",
            action_type="invoice_received",
            action_summary="Invoice INV-2001 arrived from Kepler Advisory Group for consulting services due the same day.",
            tool_name="mailroom-adapter",
            target_system="inbox",
            permission_scope="invoice:intake",
            metadata={
                **escalated_context,
                "headline": "AP inbox received a high-value same-day invoice",
                "why_it_mattered": "The amount and due date mean the workflow is operationally sensitive before any agent action happens.",
            },
        ),
        _event(
            event_id="evt_wf_2001_02",
            minutes=22,
            workflow_id="wf-invoice-2001",
            business_object_id="INV-2001",
            process_step="classification",
            actor_type=ActorType.AGENT,
            actor_id="ap-agent",
            actor_name="AP Agent",
            action_type="classify_invoice",
            action_summary="AP Agent classified the invoice as consulting spend tied to a funded transformation project.",
            tool_name="invoice-classifier",
            target_system="inbox",
            permission_scope="invoice:classify",
            parent_event_id="evt_wf_2001_01",
            metadata={
                **escalated_context,
                "headline": "Agent classified the invoice into a high-value services lane",
                "why_it_mattered": "The workflow remains eligible for agent assistance, but not for autonomous approval.",
            },
        ),
        _event(
            event_id="evt_wf_2001_03",
            minutes=25,
            workflow_id="wf-invoice-2001",
            business_object_id="INV-2001",
            process_step="po_check",
            actor_type=ActorType.AGENT,
            actor_id="ap-agent",
            actor_name="AP Agent",
            action_type="check_purchase_order",
            action_summary="AP Agent verified PO-9921, matched the service receipt, and confirmed the consulting milestone was accepted.",
            tool_name="erp-lookup",
            target_system="erp-read",
            permission_scope="erp:read:purchase_orders",
            parent_event_id="evt_wf_2001_02",
            metadata={
                **escalated_context,
                "headline": "Agent found the ERP evidence needed to proceed",
                "why_it_mattered": "The policy problem is not missing data. It is delegated authority on a high-value payment.",
            },
        ),
        _event(
            event_id="evt_wf_2001_04",
            minutes=27,
            workflow_id="wf-invoice-2001",
            business_object_id="INV-2001",
            process_step="approval_recommendation",
            actor_type=ActorType.AGENT,
            actor_id="ap-agent",
            actor_name="AP Agent",
            action_type="prepare_approval_recommendation",
            action_summary="AP Agent assembled a recommendation packet for approval with full spend context, ERP evidence, and payment cut-off timing.",
            tool_name="approval-packet-builder",
            target_system="erp-read",
            permission_scope="invoice:approve:proposal",
            authority_subject="AP Agent may prepare the finance review packet but cannot approve amounts above USD 5,000.",
            authority_delegation_source="Finance AP delegation policy v2026.03",
            parent_event_id="evt_wf_2001_03",
            metadata={
                **escalated_context,
                "headline": "Agent prepared the approval case but did not execute approval",
                "why_it_mattered": "The agent can accelerate the workflow without owning the final authority boundary.",
            },
        ),
        _event(
            event_id="evt_wf_2001_05",
            minutes=28,
            workflow_id="wf-invoice-2001",
            business_object_id="INV-2001",
            process_step="policy_gate",
            actor_type=ActorType.SYSTEM,
            actor_id="policy-engine",
            actor_name="Policy Engine",
            action_type="policy_evaluation",
            action_summary="Policy Engine escalated the approval because $18,500 exceeds the delegated $5,000 agent threshold and finance sign-off is required before the payment cut-off.",
            tool_name="policy-engine",
            target_system="policy-engine",
            permission_scope="policy:evaluate",
            review_case_id="review-wf-invoice-2001",
            review_state="pending_human_review",
            due_by=datetime(2026, 3, 31, 14, 0, tzinfo=timezone.utc),
            parent_event_id="evt_wf_2001_04",
            metadata={
                **escalated_context,
                "headline": "Policy engine escalated the workflow out of the agent lane",
                "why_it_mattered": "This is where authority changes hands from an autonomous path to a controlled human decision.",
                "review_owner_name": "Finance Director",
                "review_owner_role": "Finance Director",
                "candidate_actor_type": "agent",
                "candidate_actor_id": "ap-agent",
                "candidate_action_type": "propose_invoice_approval",
                "candidate_target_system": "erp-approvals",
            },
        ),
        _event(
            event_id="evt_wf_2001_06",
            minutes=33,
            workflow_id="wf-invoice-2001",
            business_object_id="INV-2001",
            process_step="finance_review",
            actor_type=ActorType.HUMAN,
            actor_id="finance-director-7",
            actor_name="Finance Director",
            action_type="human_approve_invoice",
            action_summary="Finance Director approved the escalated invoice after reviewing the recommendation packet, PO evidence, and same-day payment risk.",
            tool_name="finance-console",
            target_system="erp-approvals",
            permission_scope="invoice:approve:high_value",
            authority_subject="Finance Director holds final approval authority for invoices above the delegated agent threshold.",
            authority_delegation_source="Finance approval matrix FY2026",
            review_case_id="review-wf-invoice-2001",
            review_state="resolved_by_human",
            human_decision_reason="Approved because the PO and service receipt were valid and same-day payment would otherwise slip.",
            decision_code="approve_high_value_invoice",
            decision_rationale="Approved because the source-system evidence was complete, the consulting milestone was accepted, and the invoice would miss the same-day payment batch without intervention.",
            approved_exception_type="high_value_same_day_payment",
            approver_role="Finance Director",
            closure_status="approved",
            parent_event_id="evt_wf_2001_05",
            metadata={
                **escalated_context,
                "headline": "Finance Director intervened and approved the high-value invoice",
                "why_it_mattered": "The human step is explicit in the evidence trail, which makes the authority transfer reviewable later.",
            },
        ),
        _event(
            event_id="evt_wf_2001_07",
            minutes=35,
            workflow_id="wf-invoice-2001",
            business_object_id="INV-2001",
            process_step="payment_queue",
            actor_type=ActorType.SYSTEM,
            actor_id="erp",
            actor_name="ERP Scheduler",
            action_type="payment_scheduled",
            action_summary="ERP scheduled the invoice into the same-day payment run after finance approval arrived before cut-off.",
            tool_name="erp-scheduler",
            target_system="erp-approvals",
            permission_scope="invoice:payment:schedule",
            parent_event_id="evt_wf_2001_06",
            metadata={
                **escalated_context,
                "headline": "Escalation resolved without losing the payment run",
                "why_it_mattered": "The replay shows the business value of fast escalation handling, not just policy enforcement.",
                "outcome_headline": "Escalated invoice cleared finance review before the payment cut-off.",
            },
        ),
        _event(
            event_id="evt_wf_3001_01",
            minutes=45,
            workflow_id="wf-invoice-3001",
            business_object_id="INV-3001",
            process_step="invoice_received",
            actor_type=ActorType.SYSTEM,
            actor_id="ap-inbox",
            actor_name="AP Inbox",
            action_type="invoice_received",
            action_summary="Invoice INV-3001 arrived from Atlas Field Services without a PO number and with same-day payment pressure from field operations.",
            tool_name="mailroom-adapter",
            target_system="inbox",
            permission_scope="invoice:intake",
            metadata={
                **blocked_context,
                "headline": "AP inbox received an exception invoice with missing purchase order evidence",
                "why_it_mattered": "The workflow starts in a risky state because the financial obligation cannot yet be tied back to an approved purchase order.",
            },
        ),
        _event(
            event_id="evt_wf_3001_02",
            minutes=47,
            workflow_id="wf-invoice-3001",
            business_object_id="INV-3001",
            process_step="classification",
            actor_type=ActorType.AGENT,
            actor_id="ap-agent",
            actor_name="AP Agent",
            action_type="classify_invoice",
            action_summary="AP Agent classified the invoice as a non-PO field services exception that would normally require supporting documentation.",
            tool_name="invoice-classifier",
            target_system="inbox",
            permission_scope="invoice:classify",
            parent_event_id="evt_wf_3001_01",
            metadata={
                **blocked_context,
                "headline": "Agent identified an exception invoice that should not auto-clear",
                "why_it_mattered": "The agent can accelerate triage, but it still needs the policy gate to decide whether the workflow may continue.",
            },
        ),
        _event(
            event_id="evt_wf_3001_03",
            minutes=49,
            workflow_id="wf-invoice-3001",
            business_object_id="INV-3001",
            process_step="approval_recommendation",
            actor_type=ActorType.AGENT,
            actor_id="ap-agent",
            actor_name="AP Agent",
            action_type="prepare_approval_recommendation",
            action_summary="AP Agent assembled a recommendation packet even though the invoice still lacked PO support and was under same-day payment pressure.",
            tool_name="approval-packet-builder",
            target_system="erp-read",
            permission_scope="invoice:approve:proposal",
            authority_subject="AP Agent may prepare exception packets but cannot bypass missing purchasing evidence.",
            authority_delegation_source="Finance AP delegation policy v2026.03",
            parent_event_id="evt_wf_3001_02",
            metadata={
                **blocked_context,
                "headline": "Agent prepared a recommendation despite missing purchasing evidence",
                "why_it_mattered": "This is where the control layer matters: the workflow has enough momentum to continue, but not enough evidence to be safe.",
            },
        ),
        _event(
            event_id="evt_wf_3001_04",
            minutes=50,
            workflow_id="wf-invoice-3001",
            business_object_id="INV-3001",
            process_step="policy_gate",
            actor_type=ActorType.SYSTEM,
            actor_id="policy-engine",
            actor_name="Policy Engine",
            action_type="policy_evaluation",
            action_summary="Policy Engine blocked the approval path because the invoice is missing a PO number and cannot satisfy the required approval fields.",
            tool_name="policy-engine",
            target_system="policy-engine",
            permission_scope="policy:evaluate",
            review_case_id="review-wf-invoice-3001",
            review_state="pending_human_review",
            due_by=datetime(2026, 3, 31, 14, 0, tzinfo=timezone.utc),
            parent_event_id="evt_wf_3001_03",
            metadata={
                **blocked_context,
                "headline": "Policy engine blocked the workflow before approval could proceed",
                "why_it_mattered": "This is the explicit control decision that prevents an exception invoice from silently sliding into approval.",
                "review_owner_name": "AP Manager",
                "review_owner_role": "AP Manager",
                "candidate_actor_type": "agent",
                "candidate_actor_id": "ap-agent",
                "candidate_action_type": "propose_invoice_approval",
                "candidate_target_system": "erp-approvals",
            },
        ),
        _event(
            event_id="evt_wf_3001_05",
            minutes=51,
            workflow_id="wf-invoice-3001",
            business_object_id="INV-3001",
            process_step="approval_execution",
            actor_type=ActorType.AGENT,
            actor_id="ap-agent",
            actor_name="AP Agent",
            action_type="approve_invoice",
            action_summary="AP Agent still attempted to approve the invoice directly against the ERP payments surface after the policy block.",
            tool_name="erp-payment-writer",
            target_system="erp-payments",
            permission_scope="invoice:approve:under_threshold",
            authority_subject="AP Agent has no authority to approve exception invoices without a PO or to write directly to ERP payments.",
            authority_delegation_source="Finance AP delegation policy v2026.03",
            review_case_id="review-wf-invoice-3001",
            review_state="pending_human_review",
            parent_event_id="evt_wf_3001_04",
            metadata={
                **blocked_context,
                "headline": "Agent attempted a disallowed approval after the policy stop",
                "why_it_mattered": "The evidence trail now captures a concrete policy breach attempt, not just an incomplete workflow.",
            },
        ),
        _event(
            event_id="evt_wf_3001_06",
            minutes=57,
            workflow_id="wf-invoice-3001",
            business_object_id="INV-3001",
            process_step="finance_review",
            actor_type=ActorType.HUMAN,
            actor_id="ap-manager-2",
            actor_name="AP Manager",
            action_type="reject_invoice",
            action_summary="AP Manager rejected the invoice, placed it on manual hold, and requested PO support after reviewing the blocked trace and unauthorized attempt.",
            tool_name="finance-console",
            target_system="erp-approvals",
            permission_scope="invoice:reject",
            authority_subject="AP Manager may reject exception invoices and place them on manual hold pending corrective evidence.",
            authority_delegation_source="AP exception handling procedure v2026.03",
            review_case_id="review-wf-invoice-3001",
            review_state="resolved_by_human",
            human_decision_reason="Rejected because the invoice lacked a PO and the post-block approval attempt created a policy breach review.",
            decision_code="reject_missing_purchase_order",
            decision_rationale="Rejected because the invoice did not satisfy required purchasing controls and the post-block approval attempt elevated the case into a manual exception review.",
            approved_exception_type="missing_purchase_order",
            approver_role="AP Manager",
            remediation_owner="Procurement Operations",
            remediation_due_by=datetime(2026, 4, 1, 12, 0, tzinfo=timezone.utc),
            closure_status="rejected",
            parent_event_id="evt_wf_3001_05",
            metadata={
                **blocked_context,
                "headline": "AP Manager rejected the invoice and moved it to manual hold",
                "why_it_mattered": "Human intervention closes the risky path and creates a reviewable final outcome for governance and process owners.",
                "outcome_headline": "Policy stopped an unsafe approval path and AP rejected the invoice pending support.",
            },
        ),
    ]
